---
- hosts: all

  become: yes
  gather_facts: False 

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"
  
    - name: Enable EPEL
      yum: 
        name: epel-release 
        state: present 
  
    - name: Remove packages
      yum: 
        name: "{{ query('lines', 'cat packages/{{ reduce }}') }}"
        state: absent

    - name: Install packages
      yum: 
        name:
          - mc
          - less
          - htop
          - rsync
          - python36
          - vim-enhanced
          - tmux
        state: present

    - name: Install pip
      command: python3.6 -m ensurepip
