# https://www.digitalocean.com/community/tutorials/iptables-essentials-common-firewall-rules-and-commands

---
- hosts: all

  become: yes
  gather_facts: False
  
  tasks: 
    - name: Remove firewalld package
      yum: 
        name: firewalld
        state: absent
  
    - name: Install iptables-services package
      yum: 
        name: iptables-services
        state: present

    - name: Firewall - start iptables
      service:
        name: iptables
        state: started
        enabled: yes

    - name: Rules
      iptables_raw:
        name: basic_rules
        ipversion: "{{ item }}"
        keep_unmanaged: no
        rules: |
          -A INPUT -i lo -j ACCEPT
          -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
          -A INPUT -m conntrack --ctstate INVALID -j DROP
          -A INPUT -p tcp --dport {{ new_port }} -m conntrack --ctstate NEW -j ACCEPT
          -A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW -j ACCEPT
          -A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW -j ACCEPT
          -A INPUT -p tcp --dport 25 -m conntrack --ctstate NEW -j ACCEPT
          -A INPUT -p icmp -j ACCEPT
          -P INPUT DROP
          -P FORWARD DROP
          -P OUTPUT ACCEPT
      with_items: [4, 6]
